CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid varchar(128) NOT NULL,
    email varchar(320) NOT NULL,
    first_name varchar(128) NOT NULL,
    last_name varchar(128) NOT NULL,
    role text NOT NULL DEFAULT 'guest' CHECK (role IN ('host', 'guest')),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT users_firebase_uid_key UNIQUE (firebase_uid),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE INDEX users_email_idx ON users (email);
