CREATE TABLE pending_password_resets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash bytea NOT NULL,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pending_password_resets_user_id_key UNIQUE (user_id),
    CONSTRAINT pending_password_resets_token_hash_key UNIQUE (token_hash)
);

CREATE INDEX pending_password_resets_expires_at_idx ON pending_password_resets (expires_at);
