CREATE TABLE pending_signups (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(320) NOT NULL,
    first_name varchar(128) NOT NULL,
    last_name varchar(128) NOT NULL,
    role smallint NOT NULL DEFAULT 1 CHECK (role IN (0, 1)),
    encrypted_password bytea NOT NULL,
    token_hash bytea NOT NULL,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pending_signups_email_key UNIQUE (email),
    CONSTRAINT pending_signups_token_hash_key UNIQUE (token_hash)
);

CREATE INDEX pending_signups_expires_at_idx ON pending_signups (expires_at);
