CREATE TABLE IF NOT EXISTS party_signup_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id integer NOT NULL REFERENCES parties (id) ON DELETE CASCADE,
    user_id integer REFERENCES users (id) ON DELETE SET NULL,
    label text NOT NULL DEFAULT '',
    note text NOT NULL DEFAULT '',
    host_created boolean NOT NULL DEFAULT false,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS party_signup_items_party_id_idx ON party_signup_items (party_id);
CREATE INDEX IF NOT EXISTS party_signup_items_user_id_idx ON party_signup_items (user_id);
