CREATE TABLE IF NOT EXISTS event_teams (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id integer NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    name text NOT NULL,
    user_ids integer[] NOT NULL DEFAULT '{}',
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS event_teams_event_id_idx ON event_teams (event_id);
CREATE INDEX IF NOT EXISTS event_teams_user_ids_idx ON event_teams USING gin (user_ids);

ALTER TABLE images
    ADD COLUMN IF NOT EXISTS team_id integer REFERENCES event_teams (id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS images_team_id_idx ON images (team_id);
