CREATE TABLE images (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url text NOT NULL,
    date date NOT NULL,
    uploaded_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX images_date_idx ON images (date);
CREATE INDEX images_uploaded_at_idx ON images (uploaded_at);
