DO $$
BEGIN
    CREATE TYPE event_type AS ENUM ('0', '1');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL,
    party_id integer REFERENCES parties (id) ON DELETE SET NULL,
    start_date timestamptz,
    end_date timestamptz,
    completed_at timestamptz,
    type event_type NOT NULL,
    description text NOT NULL DEFAULT '',
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS events_party_id_idx ON events (party_id);
CREATE INDEX IF NOT EXISTS events_start_date_idx ON events (start_date);
CREATE INDEX IF NOT EXISTS events_type_idx ON events (type);

ALTER TABLE images
    ADD COLUMN IF NOT EXISTS event_id integer REFERENCES events (id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS user_ids integer[] NOT NULL DEFAULT '{}';

CREATE INDEX IF NOT EXISTS images_event_id_idx ON images (event_id);
CREATE INDEX IF NOT EXISTS images_user_ids_idx ON images USING gin (user_ids);

CREATE TABLE IF NOT EXISTS event_user (
    event_id integer NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    contestant boolean NOT NULL DEFAULT false,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (event_id, user_id)
);

CREATE INDEX IF NOT EXISTS event_user_user_id_idx ON event_user (user_id);
