CREATE TABLE parties (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL,
    date timestamptz NOT NULL,
    image_url text NOT NULL,
    partiful_url text NOT NULL
);
