CREATE TABLE IF NOT EXISTS event_rounds (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id integer NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    round_number integer NOT NULL,
    position integer NOT NULL,
    participant_one jsonb,
    participant_two jsonb,
    winner jsonb,
    completed_at timestamptz,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (event_id, round_number, position)
);

CREATE INDEX IF NOT EXISTS event_rounds_event_id_idx ON event_rounds (event_id);
CREATE INDEX IF NOT EXISTS event_rounds_event_round_idx ON event_rounds (event_id, round_number);
