CREATE TABLE IF NOT EXISTS party_attendees (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id integer NOT NULL REFERENCES parties (id) ON DELETE CASCADE,
    user_id integer REFERENCES users (id) ON DELETE SET NULL,
    first_name text NOT NULL DEFAULT '',
    last_name text NOT NULL DEFAULT '',
    email text NOT NULL DEFAULT '',
    plus_one_of integer REFERENCES party_attendees (id) ON DELETE CASCADE,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS party_attendees_party_user_uidx
    ON party_attendees (party_id, user_id)
    WHERE user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS party_attendees_party_id_idx ON party_attendees (party_id);
CREATE INDEX IF NOT EXISTS party_attendees_plus_one_of_idx ON party_attendees (plus_one_of);
CREATE INDEX IF NOT EXISTS party_attendees_user_id_idx ON party_attendees (user_id);
